/*
Navicat SQL Server Data Transfer

Source Server         : sqlServerCon
Source Server Version : 110000
Source Host           : 192.168.2.68:1433
Source Database       : test
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 110000
File Encoding         : 65001

Date: 2020-03-02 09:39:52
*/


-- ----------------------------
-- Table structure for SYS_EVENTLOG
-- ----------------------------
DROP TABLE [dbo].[SYS_EVENTLOG]
GO
CREATE TABLE [dbo].[SYS_EVENTLOG] (
[DWKEY] varchar(12) NOT NULL ,
[USERID] varchar(20) NULL ,
[COMPANYID] varchar(20) NULL ,
[EVENTTIME] datetime NULL ,
[EVENT] varchar(20) NULL ,
[EVENTOBJECT] varchar(4000) NULL ,
[EVENTRESULT] varchar(20) NULL ,
[USERNAME] varchar(20) NULL ,
[IPADDRESS] varchar(24) NULL ,
[MODULENAME] varchar(255) NULL 
)


GO

-- ----------------------------
-- Records of SYS_EVENTLOG
-- ----------------------------
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'yf6G401IyKcT', N'admin', null, N'2020-02-10 10:36:21.667', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'yCaNYgRMyKcT', N'admin', null, N'2020-02-10 10:36:25.547', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'v6fw8jDayKcT', N'admin', null, N'2020-02-10 10:36:27.313', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'9_1ogFxJyKcT', N'admin', null, N'2020-02-10 10:36:27.507', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'1HEZncjhyKcT', N'admin', null, N'2020-02-10 10:36:27.830', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'XxFW4WqYyKcT', N'admin', null, N'2020-02-10 10:36:28.450', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'UL23GkUQyKcT', N'admin', null, N'2020-02-10 10:36:28.763', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'TqSByc5OyKcT', N'admin', null, N'2020-02-10 10:36:29.187', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'UVIbzUxoyKcT', N'admin', null, N'2020-02-10 10:36:30.823', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'6gdlvnrtyKcT', N'admin', null, N'2020-02-10 10:36:33.867', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'24dssa40yKcT', N'admin', null, N'2020-02-10 10:36:34.483', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'skqltF3gyKcT', N'admin', null, N'2020-02-10 10:36:34.957', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'n4D7LuPxyKcT', N'admin', null, N'2020-02-10 10:36:35.937', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'L7DNXSTHyKcT', N'admin', null, N'2020-02-10 10:36:36.313', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'XcFlKrfgyKcT', N'admin', null, N'2020-02-10 10:36:39.793', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Bb0hRbzSyKcU', N'admin', null, N'2020-02-10 10:36:40.447', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'X4Ef07VuyKcU', N'admin', null, N'2020-02-10 10:37:02.333', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'ld2I2AnuyKcU', N'admin', null, N'2020-02-10 10:37:04.697', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'2Dz2MYwkyKcU', N'admin', null, N'2020-02-10 10:37:06.780', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'TI5uq8bmyKcU', N'admin', null, N'2020-02-10 10:37:07.107', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'dSVJX55jyKcU', N'admin', null, N'2020-02-10 10:37:12.203', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'_ypSU3vlyKce', N'admin', null, N'2020-02-10 10:53:42.933', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Vef6RODyyKcw', N'admin', null, N'2020-02-10 11:24:03.540', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'6cpOPRm5yKcw', N'admin', null, N'2020-02-10 11:24:06.410', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'6nwm~tYqyL0e', N'admin', null, N'2020-02-12 09:06:51.390', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'9jWJHNrGyL0e', N'admin', null, N'2020-02-12 09:06:56.280', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'i66dqUmEyL0e', N'admin', null, N'2020-02-12 09:07:01.087', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'H71M3W7ayL0e', N'admin', null, N'2020-02-12 09:07:01.607', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Gn6bWOGFyL0e', N'admin', null, N'2020-02-12 09:07:01.967', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'kWy9iHC9yL0e', N'admin', null, N'2020-02-12 09:07:02.293', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Bv5qarYZyL0e', N'admin', null, N'2020-02-12 09:07:02.627', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'6ke1Y8NmyL0h', N'admin', null, N'2020-02-12 09:13:18.607', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'oEfuXB71yLRt', N'admin', null, N'2020-02-14 09:32:25.537', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'n4fHNAZDyM6f', N'admin', null, N'2020-02-17 13:35:18.590', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'jxMTMH2ByM6g', N'admin', null, N'2020-02-17 13:37:04.383', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'1x0Tu9bjyM74', N'admin', null, N'2020-02-17 14:21:06.460', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'FBnXRlhVyM7U', N'admin', null, N'2020-02-17 15:03:41.377', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'fhT2v2EdyM7U', N'admin', null, N'2020-02-17 15:03:43.080', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'_KKQK40ZyM7U', N'admin', null, N'2020-02-17 15:03:44.847', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'gW37ccZmyM7U', N'admin', null, N'2020-02-17 15:03:47.260', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'HdRaHeBOyM7U', N'admin', null, N'2020-02-17 15:03:50.273', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'BGRJlaEGyM7U', N'admin', null, N'2020-02-17 15:03:50.887', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'pzYtR_YoyM7U', N'admin', null, N'2020-02-17 15:03:51.303', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'x7B55Ft9yM7U', N'admin', null, N'2020-02-17 15:03:57.467', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'MWzZfncqyM7U', N'admin', null, N'2020-02-17 15:04:27.397', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'V7u3c2K1yMLV', N'admin', null, N'2020-02-18 15:58:25.413', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'NLgs~C56yOOr', N'admin', null, N'2020-02-28 09:28:20.920', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'vIkmeIMhyP1Q', N'admin', null, N'2020-03-02 09:37:45.297', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'neUorWARyKce', N'admin', null, N'2020-02-10 10:53:56.037', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'5QTiM27qyKcw', N'admin', null, N'2020-02-10 11:23:58.887', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'O4vNAUlIyKcw', N'admin', null, N'2020-02-10 11:24:03.500', N'浏览信息', N'', N'成功', N'系统管理员', N'192.168.2.68', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'wzA1MEn_yM74', N'admin', null, N'2020-02-17 14:21:08.510', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'yUWaNfAYyM74', N'admin', null, N'2020-02-17 14:21:11.013', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'll1hkAWAyM74', N'admin', null, N'2020-02-17 14:21:12.720', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'YYMO~oQfyM74', N'admin', null, N'2020-02-17 14:21:13.037', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'qmI1_UaiyM74', N'admin', null, N'2020-02-17 14:21:15.713', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'x04eJPOkyM74', N'admin', null, N'2020-02-17 14:21:19.457', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'2lDRrFYYyM74', N'admin', null, N'2020-02-17 14:21:20.233', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'5T4TKT2lyM74', N'admin', null, N'2020-02-17 14:21:20.810', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'mc168z0byM74', N'admin', null, N'2020-02-17 14:21:21.260', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'xRwE9keyM74', N'admin', null, N'2020-02-17 14:21:23.677', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'4vM_x1ZvyM77', N'admin', null, N'2020-02-17 14:25:18.910', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'btIuE7ShyM77', N'admin', null, N'2020-02-17 14:25:19.750', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'rcz72XXKyM77', N'admin', null, N'2020-02-17 14:25:25.867', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'VKHSpR~vyM77', N'admin', null, N'2020-02-17 14:25:27.620', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'gXOWMEZnyM77', N'admin', null, N'2020-02-17 14:25:28.260', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Qk61ZD5jyM77', N'admin', null, N'2020-02-17 14:25:29.197', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'j6qScevRyM77', N'admin', null, N'2020-02-17 14:25:29.703', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'YezNo0JVyM77', N'admin', null, N'2020-02-17 14:25:30.800', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'EFcnBz5myM77', N'admin', null, N'2020-02-17 14:25:31.327', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'lfhM3s~pyM77', N'admin', null, N'2020-02-17 14:25:33.547', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'X_8tatmLyM77', N'admin', null, N'2020-02-17 14:25:34.030', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'Tg~9w7e_yM77', N'admin', null, N'2020-02-17 14:25:34.610', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'iefxQDwayM77', N'admin', null, N'2020-02-17 14:25:34.957', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'rO8SwpVJyM77', N'admin', null, N'2020-02-17 14:25:36.687', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'li2zU8vRyM7S', N'admin', null, N'2020-02-17 15:00:04.187', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'L6P_cyL1yM7S', N'admin', null, N'2020-02-17 15:00:13.973', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'EPPRVHRyyM7S', N'admin', null, N'2020-02-17 15:01:18.970', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'xvqKUXL4yM7S', N'admin', null, N'2020-02-17 15:01:19.630', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'6jan6goGyM7S', N'admin', null, N'2020-02-17 15:01:22.950', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'GGznV2YqyM7S', N'admin', null, N'2020-02-17 15:01:25.983', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'QuDgdODMyM7T', N'admin', null, N'2020-02-17 15:01:41.090', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'ZW3w0WX7yM7T', N'admin', null, N'2020-02-17 15:01:50.930', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'2vcY8vQCyM7T', N'admin', null, N'2020-02-17 15:01:52.287', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'b_f8mB3hyM7T', N'admin', null, N'2020-02-17 15:01:54.893', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'8~xrWrzVyM7T', N'admin', null, N'2020-02-17 15:02:02.090', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'WIKFR3hyM7T', N'admin', null, N'2020-02-17 15:02:04.863', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'_6j2tzobyM7T', N'admin', null, N'2020-02-17 15:02:05.757', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'XO5yZVdxyM7T', N'admin', null, N'2020-02-17 15:02:09.137', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'VlqEa7QEyM7T', N'admin', null, N'2020-02-17 15:02:09.913', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'LfLOz6DDyM7T', N'admin', null, N'2020-02-17 15:02:10.513', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'_lDqlqdIyM7T', N'admin', null, N'2020-02-17 15:02:10.923', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'g3FnQYHvyM7T', N'admin', null, N'2020-02-17 15:02:11.387', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'sezBpNRzyM7T', N'admin', null, N'2020-02-17 15:02:11.937', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'a5P5jRzoyM7T', N'admin', null, N'2020-02-17 15:02:12.533', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'~s0~CwR~yM7T', N'admin', null, N'2020-02-17 15:02:13.063', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'oGBGDusRyM7T', N'admin', null, N'2020-02-17 15:02:28.443', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'SzJxipYVyM7T', N'admin', null, N'2020-02-17 15:02:30.147', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'jOPrLP_RyM7T', N'admin', null, N'2020-02-17 15:02:32.347', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'B_I6ViGZyM7U', N'admin', null, N'2020-02-17 15:03:39.813', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'DMlo_8VvyMHm', N'admin', null, N'2020-02-18 09:20:12.437', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'xhTya4EAyMLU', N'admin', null, N'2020-02-18 15:58:18.193', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'HxfqLT4LyMLV', N'admin', null, N'2020-02-18 15:58:29.520', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'hPUhGF5QyMLV', N'admin', null, N'2020-02-18 15:58:31.310', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'TWDsH02_yMLV', N'admin', null, N'2020-02-18 15:58:31.640', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'u9eJhZPyyMLV', N'admin', null, N'2020-02-18 15:58:32.827', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'QQRyJqtjyMLV', N'admin', null, N'2020-02-18 15:58:33.627', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
INSERT INTO [dbo].[SYS_EVENTLOG] ([DWKEY], [USERID], [COMPANYID], [EVENTTIME], [EVENT], [EVENTOBJECT], [EVENTRESULT], [USERNAME], [IPADDRESS], [MODULENAME]) VALUES (N'QI7nc5sZyMLV', N'admin', null, N'2020-02-18 15:58:35.780', N'浏览信息', N'', N'成功', N'系统管理员', N'0:0:0:0:0:0:0:1', N'系统日志')
GO
GO
