/*
Navicat SQL Server Data Transfer

Source Server         : sqlServerCon
Source Server Version : 110000
Source Host           : 192.168.2.68:1433
Source Database       : test
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 110000
File Encoding         : 65001

Date: 2020-03-02 09:40:14
*/


-- ----------------------------
-- Table structure for SYS_RBAC_MOD2OP
-- ----------------------------
DROP TABLE [dbo].[SYS_RBAC_MOD2OP]
GO
CREATE TABLE [dbo].[SYS_RBAC_MOD2OP] (
[MODULE_ID] varchar(255) NOT NULL ,
[OPERATOR_ID] varchar(255) NOT NULL ,
[ORDERNO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of SYS_RBAC_MOD2OP
-- ----------------------------
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-AREA', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-AREA', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-AREA', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-AREA', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-CFG', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-CFG', N'modify', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ORGAN', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ORGAN', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ORGAN', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ORGAN', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-RIGHT', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-RIGHT', N'modify', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ROLE', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ROLE', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ROLE', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-ROLE', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-USER', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-USER', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-USER', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-USER', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'USERINFO-INFO', N'modify', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'USERINFO-PWD', N'modify', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-DICT', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-DICT', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-DICT', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-DICT', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-LOG', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-LOG', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-LOG', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'SYS-LOG', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-CONFIG', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-CONFIG', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-CONFIG', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-CONFIG', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-FORWARD', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-FORWARD', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-FORWARD', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-FORWARD', N'delete', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-LOG', N'view', N'1')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-LOG', N'add', N'2')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-LOG', N'modify', N'3')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MOD2OP] ([MODULE_ID], [OPERATOR_ID], [ORDERNO]) VALUES (N'DATASOURCE-LOG', N'delete', N'4')
GO
GO
