/*
Navicat SQL Server Data Transfer

Source Server         : sqlServerCon
Source Server Version : 110000
Source Host           : 192.168.2.68:1433
Source Database       : test
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 110000
File Encoding         : 65001

Date: 2020-03-02 09:40:20
*/


-- ----------------------------
-- Table structure for SYS_RBAC_MODRIGHT
-- ----------------------------
DROP TABLE [dbo].[SYS_RBAC_MODRIGHT]
GO
CREATE TABLE [dbo].[SYS_RBAC_MODRIGHT] (
[MODULE_ID] varchar(255) NOT NULL ,
[ROLE_ID] varchar(255) NOT NULL ,
[RIGHT_VALUE] numeric(10) NULL 
)


GO

-- ----------------------------
-- Records of SYS_RBAC_MODRIGHT
-- ----------------------------
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-CONFIG', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-CFG', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-INFO', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-PWD', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-DICT', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-FORWARD', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-LOG', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-AREA', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ORGAN', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ROLE', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-RIGHT', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-USER', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-CFG', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-LOG', N'SYS_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-PWD', N'BASE_ROLE', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-INFO', N'BASE_ROLE', N'4')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-CONFIG', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-CFG', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-INFO', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-PWD', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-DICT', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-FORWARD', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-LOG', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-AREA', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ORGAN', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ROLE', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-RIGHT', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-USER', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-LOG', N'SUPER_ROLE', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-INFO', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-PWD', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-DICT', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-FORWARD', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-LOG', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-AREA', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ORGAN', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ROLE', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-RIGHT', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-USER', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-LOG', N'N4Se07vayMLf', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-CONFIG', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-CFG', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-INFO', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'USERINFO-PWD', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-DICT', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-FORWARD', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'DATASOURCE-LOG', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-AREA', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ORGAN', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-ROLE', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-RIGHT', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-USER', N'Md98wqQjyLRk', N'2147483647')
GO
GO
INSERT INTO [dbo].[SYS_RBAC_MODRIGHT] ([MODULE_ID], [ROLE_ID], [RIGHT_VALUE]) VALUES (N'SYS-LOG', N'Md98wqQjyLRk', N'2147483647')
GO
GO
